### ISSUE TITLE
Sum row doesn't update as we make changes to the poll

### ISSUE THREAD

**Issue by amandee27** [Morphclue/apollusia#194]
# Context
When we interact with a poll, the 'Sum' row doesn't update immediately as we are adding participants and making preferences. It only updates after the page reloads.

## Steps to Reproduce
1. Create a new poll with the 'Group' preset (show results to participants immediately)
2. Open the poll link in another window
3. Add new participants and select preferences
4. Notice that 'Sum' row doesn't update when we are making changes

## Expected result
Need to see aggregated results in 'Sum' row immediately

## Actual result
'Sum' row does not change. It change only after page reload

## References

![buugDemo (1)](https://github.com/user-attachments/assets/0edd93cf-54cd-4cb5-8929-3e849123444e)

**Comment by amandee27** [comment]
@Morphclue  Happy to work on this issue if you can verify the issue and assign this to me.

**Comment by Morphclue** [comment]
@amandee27 Sure! If you need any help or some guidance feel free to ask.
