### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by Morphclue** [Morphclue/apollusia#29]
# Context
The settings should hold an option to activate darkmode.
It might be necessary to redesign the lightmode color-palette.

## References
* [ng-bootstrap-darkmode](https://github.com/Clashsoft/ng-bootstrap-darkmode)

**Comment by Clashsoft** [comment]
Bootstrap 5.3 (Alpha) has a new native darkmode (https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/), maybe we can use that.

**Comment by Clashsoft** [comment]
Closed by #85
