### ISSUE TITLE
Save Settings Modal reloads the page

### ISSUE THREAD

**Issue by Clashsoft** [Morphclue/apollusia#44]
This behavior is a little suboptimal and should be avoided since we have a single-page application.

A problematic workflow:

- Create a poll
- Enter some data
- Try to activate admin updates
- Realize mail is not configured (banner)
- Click Configure
- Enter email in modal
- Save
- Data for new poll is gone :(

**Comment by sh0xy** [comment]
I just realized the same behaviour.
With the little addition that if you click save the page reloads AND the modal pops up again.
You can repeat indefinitely.
You have to close the popup on 'X' to leave the window.
