### ISSUE TITLE
Location of titles/polls on the dashboard

### ISSUE THREAD

**Issue by UeberallGebannt** [Morphclue/apollusia#59]
# Context
A lot of the following really comes down to personal preference, so this should most likely be considered low priority.

Due to the current formatting of the main page (dashboard), there is no visible/clear border between your own polls (My polls) and the ones where you participated in (or any of the other sections in general).

Also, if there are more than a few polls, it becomes a bit messy and harder to find the one you're looking for.

![grafik](https://user-images.githubusercontent.com/50475262/224728108-f71459e0-5479-4336-98c8-b088f95e99b3.png)

## Alternatives
I think it would be nicer to have a visible border between the sections, for example by moving the headlines from the left between the different sections. 

As there now is a wide gap on the left, it could be used for a small preview list, where you can filter/hide or goto different categories. 

- [X] My polls
   - Example poll 1
- [ ] My Participations 
- [ ] Inactive Polls 

## References
Example image with inline headlines
![grafik](https://user-images.githubusercontent.com/50475262/224729192-babf83bd-d7b1-4f3f-868d-e345341add13.png)

**Comment by Morphclue** [comment]
Thank you for the feedback! This definitely seems like a good idea to revisit the whole design. However, I'm currently still busy with my master thesis and other things and could only take on the matter from ~June. The issue itself could be fixed quickly, but I would probably change the whole design in general. But I agree with you that the dashboard currently still looks unclear. Spontaneously I would think of tabs to structure the categories. That would prevent the long scrolling and also simplify your filter proposal for mobile application. Of course, the best solution can be determined only through extensive user testing.

**Comment by UeberallGebannt** [comment]
You're right, a tab based system would be even better.
Also, good luck on your thesis!

**Comment by Clashsoft** [comment]
@UeberallGebannt I worked on this:

![image](https://user-images.githubusercontent.com/4145923/235378051-6532e0a6-a5a1-4e59-86cb-7cf74de63879.png)

Let us know what you think.

**Comment by UeberallGebannt** [comment]
Looks good to me, especially with the latest changes!
