### ISSUE TITLE
Scrolling disabled sometimes

### ISSUE THREAD

**Issue by Morphclue** [Morphclue/apollusia#62]
# Context
Two students reported that scrolling isn't working for them when they try to participate in a blind poll and didn't enter their name.
It is not clear wether this is related to any of this.

## Steps to Reproduce
This needs to be documented. I have no clue how this behaviour can be reproduced currently.

## Expected result
Scrolling should be always possible.

## Actual result
Scrolling with the HScrollBar isn't possible.

**Comment by sh0xy** [comment]
Tested on Android Tablet (Xiaomi Pad 5) on Firefox. 

Actually scrolling is working but the touch accuracy on tablet is just super sensitive so you always end up moving the site a little up or down. When the site is "moving" you cannot scroll to the left or right.

So I guess once V scrollbar is triggered you cannot use H scrollbar anymore.

**Comment by Morphclue** [comment]
Thanks for the feedback. That makes total sense and is probably the reason, why the students couldn't scroll.
If I find time after my master's thesis, I'll take care of a useful solution right away.

**Comment by Clashsoft** [comment]
This happened when clicking X instead of allowing cookies. The banner would become invisible but still consume click events. Fixed as of 6824161dc586aa6e9cda62eba8d532c115604358.
